name: tests

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Prepare dependencies
        run: |
          go mod download

      - name: Build
        run: make build

      - name: Test code
        run: |
          go test -race ./...
